### ISSUE TITLE
Implementation of ReconnectingConnectionPool ?

### ISSUE THREAD

**Issue by GMLudo** [wulczer/txpostgres#23]
Hi,

I'm a newbie with txpostgres, but a feature is missing for me, it's an automatic reconnection pool, as described here for adbapi:
http://www.gelens.org/2009/09/13/twisted-connectionpool-revisited/

From my point of view, it's an important feature in a daemon, I don't understand isn't standard in adbapi.

With txpostgres, I've read some discussions about this in #18 and #20 but nothing to implement this directly inside txpostgres.

Why it isn't implemented in txpostgres ? Lack of time to do this, or it's a mistake to implement a generic reconnecting connection pool ?

Thanks for your answer.

Regards.

**Comment by wulczer** [comment]
I just released 1.4.0 (1.3.0 was a little disaster, I tagged a commit that's not reachable from master and also included some misguided code there).

Closing this issue, since reconnection is now easy to implement in user code, using the primitives I described (look at tests for guidance on exactly how).
