### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by oberstet** [wulczer/txpostgres#40]
Would be awesome to make `txpostres` work on Python 3.3+

**Comment by wulczer** [comment]
I deferred supporting Python 3 while Twisted itself didn't support it, but I think the state of the art has changed on that... I'll re-check if parts of Twisted that txpostgres uses are Python 3 compatible already.

**Comment by oberstet** [comment]
@wulczer awesome! Should you run into missing parts, please let me know - as I might be able to arrange things to get quickly ported (@hawkowl is working on Crossbar.io and she did a lot of Twisted Python 3 porting work, and is Twisted release manager).

**Comment by wulczer** [comment]
So... it turned out the hardest part in supporting Python 3 was getting the Travis build to pass :)

All tests on `master` now pass on Python 3.4 and 3.5 locally, and on 3.5 in Travis. Note that `txpostres` now dropped Python 2.5 compatibility, which I believe is fine - I'm supporting whatever Twisted is supporting at the moment and they even dropped Python 2.6 recently...

I'm going to let this sit in `master` for a few days and then release it as `1.6.0`.

**Comment by oberstet** [comment]
@wulczer awesome! this is great news. Looking forward to the next release. Thanks!

**Comment by hawkowl** [comment]
> All tests on master now pass on Python 3.4 and 3.5 locally, and on 3.5 in Travis.

Amazing! Thanks :D

I swear I need some sort of page for Twisted ecosystem projects ported to 3...

> I'm supporting whatever Twisted is supporting at the moment and they even dropped Python 2.6 recently...

Yep!

**Comment by wulczer** [comment]
Welp, I released `1.6.0` with Python 3 compat. Thanks for nudging me to work on it, it was much easier than I expected!

**Comment by oberstet** [comment]
@wulczer fantastic. thank you so much!
